/* *****************************************************************************

    Copyright (C) 2011 Jaroslaw Czekalski - jarekczek@poczta.onet.pl

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
   *****************************************************************************
*/

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPbn.java
 *
 * Created on May 2, 2011, 4:15:37 PM
 */

package jc.pbntools;
import javax.swing.*;
import jc.f;

/**
 *
 * @author root
 */
 
public class DlgPbn extends javax.swing.JDialog
                    implements javax.swing.event.ListSelectionListener {

    PbnFile m_plik;

    /** Creates new form DlgPbn */
    public DlgPbn(java.awt.Frame parent, boolean modal, PbnFile plik) {
        super(parent, modal);
        m_plik = plik;
        initComponents();

        stLiczbaRozdan.setText("" + m_plik.m_ar.size());
        stDealer.setText("");
        stVulner.setText("");
        jList1.setModel(new DefaultListModel());
        for (int i=0; i<m_plik.m_ar.size(); i++) { ((DefaultListModel)jList1.getModel()).addElement(m_plik.m_ar.get(i)); }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PbnTools.setWindowIcons(this);
        setTitle(String.format(PbnTools.m_res.getString("pbnFile.title"),
                 m_plik.m_sPlik));

        pbZamknij = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stLiczbaRozdan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stDealer = new javax.swing.JLabel();
        stVulner = new javax.swing.JLabel();
        pbRozdaj = new javax.swing.JButton();
        pbArkusz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        f.setTextAndMnem(pbZamknij, "close");
        pbZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbZamknijActionPerformed(evt);
            }
        });

        jLabel1.setText(PbnTools.m_res.getString("pbnFile.handCount"));
        stLiczbaRozdan.setText("jLabel3");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(this);
        jScrollPane1.setViewportView(jList1);

        jLabel3.setText(PbnTools.m_res.getString("pbnFile.dealer"));

        jLabel4.setText(PbnTools.m_res.getString("pbnFile.vulnerable"));

        stDealer.setText("jLabel5");
        stVulner.setText("jLabel5");

        f.setTextAndMnem(pbRozdaj, "pbnFile.dealCards");
        pbRozdaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbRozdajActionPerformed(evt);
            }
        });

        f.setTextAndMnem(pbArkusz, "pbnFile.sheet");
        pbArkusz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbArkuszActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stVulner, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(stDealer, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pbRozdaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pbArkusz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(pbZamknij)
                            .addComponent(stLiczbaRozdan))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(stLiczbaRozdan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stDealer)
                                .addGap(18, 18, 18)
                                .addComponent(stVulner))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addGap(56, 56, 56)
                        .addComponent(pbRozdaj)
                        .addGap(18, 18, 18)
                        .addComponent(pbArkusz)))
                .addGap(18, 18, 18)
                .addComponent(pbZamknij)
                .addContainerGap())
        );

        pack();
        valueChanged(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pbZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbZamknijActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_pbZamknijActionPerformed

    private void pbRozdajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbRozdajActionPerformed
        // TODO add your handling code here:
      Deal r = (Deal) jList1.getSelectedValue();
      if (r!=null) {
        r.rozdaj();
        }
    }//GEN-LAST:event_pbRozdajActionPerformed

    private void pbArkuszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbArkuszActionPerformed
        // TODO add your handling code here:
      m_plik.arkusz();
    }//GEN-LAST:event_pbArkuszActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
                PbnFile plik = new PbnFile();
                plik.wczytaj(args[0]+"");
                DlgPbn dialog = new DlgPbn(new javax.swing.JFrame(), true, plik);
                dialog.setVisible(true);
    }
    
    public void valueChanged(javax.swing.event.ListSelectionEvent e) {
      Deal r = (Deal) jList1.getSelectedValue();
      pbRozdaj.setEnabled(r != null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pbArkusz;
    private javax.swing.JButton pbRozdaj;
    private javax.swing.JButton pbZamknij;
    private javax.swing.JLabel stDealer;
    private javax.swing.JLabel stLiczbaRozdan;
    private javax.swing.JLabel stVulner;
    // End of variables declaration//GEN-END:variables

}

// jedit options: :folding=explicit:encoding=windows-1250:tabSize=2:noTabs=true:

