/* *****************************************************************************

    Copyright (C) 2011 Jaroslaw Czekalski - jarekczek@poczta.onet.pl

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
   *****************************************************************************
*/

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPbnOpen.java
 *
 * Created on May 2, 2011, 2:26:31 PM
 */

/**
 *
 * @author root
 */
 
package jc.pbntools;
import jc.f;

import javax.swing.*;
import java.io.*;

public class DlgPbnOpen extends javax.swing.JDialog {

    /** Creates new form DlgPbnOpen */
    public DlgPbnOpen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PbnTools.setWindowIcons(this);

        ebPlik = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pbPlik = new javax.swing.JButton();
        pbOtworz = new javax.swing.JButton();
        pbAnuluj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(PbnTools.m_res.getString("openPbnFile.title"));

        ebPlik.setText(PbnTools.m_props.getProperty("openPbn.file"));
        ebPlik.selectAll();


        f.setTextAndMnem(jLabel1, PbnTools.getRes(), "pbnFile.label");

        pbPlik.setAction(new f.OpenFileAction(ebPlik));

        f.setTextAndMnem(pbOtworz, PbnTools.m_res, "open");
        pbOtworz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbOtworzActionPerformed(evt);
            }
        });

        f.setTextAndMnem(pbAnuluj, PbnTools.m_res, "cancel");
        pbAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbAnulujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ebPlik, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pbPlik))
                            .addComponent(jLabel1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pbOtworz)
                        .addGap(80, 80, 80)
                        .addComponent(pbAnuluj)
                        .addGap(221, 221, 221))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ebPlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbPlik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbOtworz)
                    .addComponent(pbAnuluj))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pbAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbAnulujActionPerformed
        this.dispose();
    }//GEN-LAST:event_pbAnulujActionPerformed

    private void pbOtworzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbOtworzActionPerformed
         String sPlik = ebPlik.getText();
         PbnFile plik = new PbnFile();
         int rv2 = plik.wczytaj(sPlik);
         if (rv2==-1) { JOptionPane.showMessageDialog(null, "Plik "+sPlik+" nie zosta� znaleziony"); }
         else if (rv2!=0) { JOptionPane.showMessageDialog(null, "Podczas odczytywania pliku "+sPlik+" wyst�pi� b��d"); }
         else {
           PbnTools.m_props.setProperty("openPbn.file", ebPlik.getText());
           this.dispose();
           DlgPbn dlgPbn = new DlgPbn(null, true, plik);
           dlgPbn.setVisible(true);
           }
    }//GEN-LAST:event_pbOtworzActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPbnOpen dialog = new DlgPbnOpen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ebPlik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pbAnuluj;
    private javax.swing.JButton pbOtworz;
    private javax.swing.JButton pbPlik;
    // End of variables declaration//GEN-END:variables

}
