/* *****************************************************************************

    Copyright (C) 2011 Jaroslaw Czekalski - jarekczek@poczta.onet.pl

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
   *****************************************************************************
*/

package jc.pbntools;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgPobierzBbo.java
 *
 * Created on 2010-03-21, 20:22:02
 */

/**
 *
 * @author Administrator
 */
public class DlgPobierzBbo extends javax.swing.JDialog {
  int rv;
  String m_sLink;

    /** Creates new form DlgPobierzBbo */
    public DlgPobierzBbo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rbLinkStateChanged(null);
        rv = 0;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PbnTools.setWindowIcons(this);

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbLink = new javax.swing.JRadioButton();
        rbOstWronie = new javax.swing.JRadioButton();
        stLink = new javax.swing.JLabel();
        ebLink = new javax.swing.JTextField();
        pbOk = new javax.swing.JButton();
        pbAnuluj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pobierz BBO");

        buttonGroup1.add(rbLink);
        rbLink.setText("z linka");
        rbLink.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbLinkStateChanged(evt);
            }
        });

        buttonGroup1.add(rbOstWronie);
        rbOstWronie.setText("ostatnie Wronie na maksy");

        stLink.setText("<html>Link do turnieju:");

        pbOk.setText("Pobierz");
        pbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbOkActionPerformed(evt);
            }
        });

        pbAnuluj.setText("Anuluj");
        pbAnuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbAnulujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbOstWronie)
                            .addComponent(rbLink)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ebLink, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(stLink))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(pbOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(pbAnuluj)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rbLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbOstWronie)
                .addGap(18, 18, 18)
                .addComponent(stLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ebLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbOk)
                    .addComponent(pbAnuluj))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbLinkStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbLinkStateChanged
        // TODO add your handling code here:
        ebLink.setVisible(rbLink.isSelected());
        stLink.setVisible(rbLink.isSelected());
    }//GEN-LAST:event_rbLinkStateChanged

    private void pbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbOkActionPerformed
        // TODO add your handling code here:
        if (!rbLink.isSelected() && !rbOstWronie.isSelected()) {
          { javax.swing.JOptionPane.showMessageDialog(null, "Nie wybra³eœ akcji"); return; }
        }
        if (rbLink.isSelected()) {
          m_sLink = ebLink.getText();
          if (m_sLink.isEmpty()) { javax.swing.JOptionPane.showMessageDialog(null, PbnTools.m_res.getString("error.emptyLink")); return; }
        }
        else {
          m_sLink = null;
        }
        rv = 2;
        dispose();
}//GEN-LAST:event_pbOkActionPerformed

    private void pbAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbAnulujActionPerformed
        // TODO add your handling code here:
        rv = -1;
        dispose();
}//GEN-LAST:event_pbAnulujActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPobierzBbo dialog = new DlgPobierzBbo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField ebLink;
    private javax.swing.JButton pbAnuluj;
    private javax.swing.JButton pbOk;
    private javax.swing.JRadioButton rbLink;
    private javax.swing.JRadioButton rbOstWronie;
    private javax.swing.JLabel stLink;
    // End of variables declaration//GEN-END:variables

}
