/* *****************************************************************************

    jedit options: :folding=explicit:tabSize=2:indentSize=2:noTabs=true:

    Copyright (C) 2026 Jaroslaw Czekalski - jarekczek@poczta.onet.pl

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
   *****************************************************************************
*/

package jc.pbntools.download;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import jc.JCException;
import jc.SoupProxy;
import jc.f;
import jc.outputwindow.SimplePrinter;
import jc.pbntools.Card;
import jc.pbntools.Deal;
import jc.pbntools.PbnTools;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TourCalcTourDownloader extends HtmlTourDownloader {
  private static Logger log = LoggerFactory.getLogger(TourCalcTourDownloader.class);

  /**
   * each deal is in file m_sDealPrefix + "nnn.html"
   */
  private String m_sDealPrefix = "p";

  private Document m_settingsDoc;

  public String getName() {
    return "TourCalc";
  }

  @Override
  public void setOutputWindow(SimplePrinter ow) {
    m_ow = ow;
  }

  @Override
  public SimplePrinter getOutputWindow() {
    return m_ow;
  }

  /**
   * Gets remote link for the deal with the given number
   */
  protected String getLinkForDeal(int iDeal) {
    return m_sLink.replaceFirst("/[^/]*$", "/" + m_sDealPrefix
      + String.format("%d.json", iDeal));
  }

  /**
   * Gets local link for the deal with the given number
   */
  protected String getLocalLinkForDeal(int iDeal) {
    return getLocalFile(getLinkForDeal(iDeal));
  }

  /**
   * @param doc Document after redirection, containing 2 frames.
   *
   */
  protected void getNumberOfDeals(Document doc, boolean bSilent)
    throws DownloadFailedException {
    ObjectMapper om = new ObjectMapper();
    try {
      Map<String, Object> settingsMap = om.readValue(m_settingsDoc.text(), Map.class);
      ArrayList<Integer> dealNumbers = (ArrayList<Integer>) settingsMap.get("BoardsNumbers");
      m_cDeals = dealNumbers.size();
    } catch (JsonProcessingException e) {
      throw new DownloadFailedException(e, m_ow, !bSilent);
    }
  }

  /**
   * Verifies whether link points to a valid data in this format.
   * Sets m_sTitle and m_sDirName members. Leaves m_doc filled.
   */ //{{{
  protected boolean verifyDirect(boolean bSilent) {
    Document doc;
    SoupProxy proxy = new SoupProxy();
    try {
      doc = proxy.getDocument(m_sLink);
      m_doc = doc;
      m_remoteUrl = proxy.getUrl();
    } catch (JCException e) {
      m_ow.addLine(e.getMessage());
      return false;
    }
    if (!bSilent)
      println(PbnTools.m_res.getString("msg.documentLoaded"));

    if (!checkMeta(doc, "generated by Tournament Calculator", bSilent)) return false;
    if (!checkLiveResultsElem(doc, bSilent)) return false;

    try {
      String settingsLink = m_sLink.replaceFirst("[^/]*$", "settings.json");
      m_settingsDoc = proxy.getDocument(settingsLink);
    } catch (JCException e2) {
      m_ow.addLine(e2.getMessage());
      return false;
    }

    return true;
  } //}}}

  protected boolean checkMeta(Document doc, String sExpValue, boolean bSilent) {
    Element elem = getOneTag(doc.head(), "meta[property=og:description]", bSilent);
    if (elem == null) {
      return false;
    }
    String sFound = elem.attr("content");
    if (sFound.isEmpty()) {
      if (!bSilent || f.isDebugMode()) {
        println(PbnTools.getStr("error.tagNotFound", "<meta name=\"og:description\" content="));
        return false;
      }
    }
    if (!sFound.contains(sExpValue)) {
      if (!bSilent || f.isDebugMode()) {
        println(PbnTools.getStr("error.invalidTagValue", "<meta name=\"og:description\" content=~",
          sExpValue, sFound));
        return false;
      }
    }
    return true;
  }

  protected boolean checkLiveResultsElem(Document doc, boolean bSilent) {
    Element elem = getOneTag(doc, "span[id=liveResultsText]", bSilent);
    return elem != null;
  }

  public boolean verify(String sLink, boolean bSilent) {
    setLink(sLink);
    if (!verifyDirect(bSilent)) {
      return false;
    }
    getTitleAndDir();
    try {
      getNumberOfDeals(m_doc, bSilent);
    } catch (DownloadFailedException dfe) {
      return false;
    }
    if (!bSilent) {
      println(PbnTools.getStr("msg.tourFound", m_sTitle, m_cDeals));
    }

    return true;
  }

  protected String createIndexFile() throws DownloadFailedException {
    int iDeal;
    String sLinksFile = new File(m_sLocalDir, "links.txt").getAbsolutePath();
    println(PbnTools.getStr("tourDown.msg.creatingIndex", sLinksFile));
    try {
      createLocalDir();
      BufferedWriter fw = new BufferedWriter(new OutputStreamWriter(
        new FileOutputStream(sLinksFile), "ISO-8859-1"));
      fw.write(m_remoteUrl.toString());
      fw.newLine();
      fw.write(m_sLink.replaceFirst("/[^/]*$", "/content-script.js"));
      fw.newLine();
      fw.write(m_sLink.replaceFirst("/[^/]*$", "/main.js"));
      fw.newLine();
      for (iDeal = 1; iDeal <= m_cDeals; iDeal++) {
        String sDealLink = getLinkForDeal(iDeal);
        fw.write(sDealLink);
        fw.newLine();
      }
      fw.close();
    } catch (java.io.IOException ioe) {
      throw new DownloadFailedException(ioe, m_ow, !m_bSilent);
    }
    return sLinksFile;
  }

  protected void wget() throws DownloadFailedException {
    String sLinksFile = createIndexFile();
    wgetLinks(sLinksFile);

    if (Thread.currentThread().isInterrupted())
      return;

    print(PbnTools.getStr("tourDown.msg.ajaxProgress"));
    for (int iDeal = 1; iDeal <= m_cDeals; iDeal++) {
      ajaxFile(getLinkForDeal(iDeal), true);
      print(".");
      if (Thread.currentThread().isInterrupted())
        return;
    }
    println("");
  }

  protected Deal[] readDealsFromDir(String sDir)
    throws DownloadFailedException {
    ArrayList<Deal> deals = new ArrayList<Deal>();
    for (int iDeal = 1; iDeal <= m_cDeals; iDeal++) {
      if (Thread.interrupted()) {
        println(PbnTools.getStr("msg.interrupted"));
        break;
      }
      Deal ad[] = readDeals(getLocalLinkForDeal(iDeal), false);
      if (ad != null) {
        for (Deal d : ad) {
          d.setIdentField("Event", m_sTitle);
          deals.add(d);
        }
        if (PbnTools.getVerbos() > 0) {
          println(PbnTools.getStr("tourDown.msg.readOne",
            iDeal, ad.length));
        }
      }
    }
    return deals.toArray(new Deal[0]);
  }

  public Deal[] readDeals(String sUrl, boolean bSilent)
    throws DownloadFailedException {
    // See main.js and declarerToString.
    char[] dealerFromDeclarer = new char[]{'N', 'S', 'W', 'E'};
    String[] vulnerabilities = new String[]{"None", "NS", "EW", "All"};

    Document doc;
    m_sCurFile = sUrl;
    m_bSilent = bSilent;

    resetErrors();
    Deal deal = new Deal();
    try {
      SoupProxy proxy = new SoupProxy();
      doc = proxy.getDocument(sUrl);
      ObjectMapper om = new ObjectMapper();
      JsonNode root = om.readTree(doc.text());
      JsonNode distribution = JsonHelper.nodeAt(root, "/ScoringGroups/0/Distribution");
      // They call it declarer, but apparently it's dealer (see declarerToString in main.js).
      int declarer = JsonHelper.nodeAt(distribution, "/_handRecord/_declarer").asInt();
      deal.setNumber(JsonHelper.nodeAt(distribution, "/Number").asInt());
      deal.setDealer(Deal.person(dealerFromDeclarer[declarer]));
      int vulnerability = JsonHelper.nodeAt(distribution, "/_handRecord/Vulnerability").asInt();
      deal.setVulner(vulnerabilities[vulnerability]);
      setCards(deal, JsonHelper.nodeAt(distribution, "/_handRecord"));
    } catch (JCException | JsonProcessingException e) {
      log.debug("", e);
      throw new DownloadFailedException(e, m_ow, !m_bSilent);
    }
    return new Deal[] { deal };
  }

  private void setCards(Deal deal, JsonNode hands) throws JcJsonException {
    String persons[] = {"N", "E", "S", "W"};
    String suits[] = {"Clubs", "Diamonds", "Hearts", "Spades"};
    for (String person : persons) {
      JsonNode hand = JsonHelper.nodeAt(hands, "/Hand" + person);
      for (String suit : suits) {
        String cardsInSuit = JsonHelper.nodeAt(hand, "/" + suit).asText()
          .toUpperCase().replace("10", "T");
        for (char ch : cardsInSuit.toCharArray()) {
          Card card = new Card();
          card.setColor(suit.charAt(0));
          card.setRankCh(ch);
          deal.setCard(card, Deal.person(person));
        }
      }
    }
    deal.fillHands();
  }

}